### PR TITLE
Fail fast if still cannot find the commit after fetch

### LINKED ISSUE #185: error packfile does not match index
```
fatal: Not a valid branch point: '865586f5d84122e04c205402831695f9fcd067c5'.
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: refs/remotes/origin/tvos_profiles does not point to a valid object!
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
/Users/distiller/.fastlane_bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: git '--git-dir=/Users/distiller/fastlane/.git' '--work-tree=/Users/distiller/fastlane' diff '--numstat' 'danger_head' 'danger_base'  2>&1:fatal: ambiguous argument 'danger_base': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'. Updating the Danger gem might fix the issue.

 #  from Dangerfile:1
 #  -------------------------------------------
 >  warn("Big PR") if lines_of_code > 500
```

Via https://circleci.com/gh/fastlane/fastlane/1533

No changes from our setup, this just happened.

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This PR changes the behavior of ensure commit exists. Fixes #185 /cc @KrauseFx @jeroenvisser101

Before we failed untill [we are finding the merge base](https://github.com/danger/danger/blob/50afd1743d1228b1c7031eb7e32eeda91aad526b/lib/danger/scm_source/git_repo.rb#L13-L15) for commits that not exists.

```ruby
ensure_commitish_exists!(from)
ensure_commitish_exists!(to)
merge_base = repo.merge_base(from, to) # <--- failed here *before* this PR
```

Now we fail fast:

```ruby
ensure_commitish_exists!(from) # <--- failed here *after* this PR
ensure_commitish_exists!(to)
merge_base = repo.merge_base(from, to) 
```

--

<details>
<summary>Cases that commits not exist happened</summary>

- Run `danger pr https://github.com/artsy/eigen/pull/1811` on `danger/danger`

  ```
  Running your Dangerfile against this PR - https://github.com/artsy/eigen/pull/1811
  Turning on --verbose

  fatal: Not a valid branch point: 'df9db51d75a5fbffaea30e3f71d39c7ddb880c26'.
  fatal: Not a valid branch point: 'b033d903cb1b3427a4c0da601b445afd7e6b9398'.
  /Users/juanitofatas/.gem/ruby/2.3.1/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/Users/juanitofatas/dev/danger/.git' '--work-tree=/Users/juanitofatas/dev/danger' merge-base 'danger_base' 'danger_head'  2>&1:fatal: Not a valid object name danger_base (Git::GitExecuteError)
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/danger-3.5.3/lib/danger/scm_source/git_repo.rb:71:in `merge_base'
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/danger-3.5.3/lib/danger/scm_source/git_repo.rb:61:in `merge_base'
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/danger-3.5.3/lib/danger/scm_source/git_repo.rb:15:in `diff_for_folder'
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/danger-3.5.3/lib/danger/commands/pr.rb:106:in `run'
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
    from /Users/juanitofatas/.gem/ruby/2.3.1/gems/danger-3.5.3/bin/danger:5:in `<top (required)>'
    from /Users/juanitofatas/.gem/ruby/2.3.1/bin/danger:22:in `load'
    from /Users/juanitofatas/.gem/ruby/2.3.1/bin/danger:22:in `<main>'
  ```

- Git rebase then force pushed
- Git reset then force pushed
</details>

### CODE REVIEW

**Comment by orta** [comment]
Yep - this makes a lot of sense to me, I literally did this while working on https://github.com/danger/danger/pull/625

File: lib/danger/scm_source/git_repo.rb [hunk 1]
```diff
@@ -38,13 +38,21 @@ def origins
...
     end
 
     private
 
     def default_env
       { "LANG" => "en_US.UTF-8" }
     end
+
+    def raise_if_we_cannot_find_the_commit(commit)
+      raise "Commit #{commit[0..7]} doesn't exists. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed."
```
Comment (JuanitoFatas) [inline lib/danger/scm_source/git_repo.rb]: Thanks for my poor English 😄
