### PR TITLE
Fix inline github comments when diff has trailing tabs

### LINKED ISSUE #1010: When importing a dangerfile from git, the inline messages are not shown
# Report

## What did you do?

My danger setup has a single shared base Dangerfile, that's imported like this:

```
danger.import_dangerfile(github: 'mobile/danger')
```

I then have some shared rules that run entirely within the shared Dangerfile. However, the file/line comments for both warn and fail actions do not post inline in the PR.

All I get is this:

screen shot 2018-08-14 at 1 27 46 pm

I have double checked that both the filename and line number appear to be correct:

screen shot 2018-08-14 at 1 42 30 pm

screen shot 2018-08-14 at 1 42 36 pm

## What did you expect to happen?

Running a rule implemented in a dangerfile that's imported via git should be able to post inline messages to the original commit.

## What happened instead?

Only posted the "summary" message.

## Your Environment

* Which CI are you running on?
  * Jenkins
* Are you running the latest version of Danger?
  * 5.5.11

### PR DESCRIPTION
**Pull request by daniel-beard**
- Fixes an issue where if a filename in the `+++` or `---` lines contains a space, an additional tab is appended to the end of the line before the newline character [reference to source](https://github.com/git/git/blob/6e0cc6776106079ed4efa0cc9abace4107657abf/diff.c#L1491)
- I believe this fixes #1010 #1042 and potentially https://github.com/ashfurrow/danger-ruby-swiftlint/issues/115

### CODE REVIEW

File: lib/danger/request_sources/github/github.rb [hunk 1]
```diff
@@ -375,6 +375,12 @@ def find_position_in_diff(diff_lines, message, kind)
         pattern = "+++ b/" + message.file + "\n"
         file_start = diff_lines.index(pattern)
 
+        # Files containing spaces sometimes have a trailing tab
+        if file_start.nil?
+          pattern = "+++ b/" + message.file + "\t\n"
+          file_start = diff_lines.index(pattern)
```
Comment (daniel-beard) [inline lib/danger/request_sources/github/github.rb]: I could simplify this entire block down to: 

```ruby
pattern = "+++ b/" + message.file + "\n"
pattern_with_tab = "+++ b/" + message.file + "\t\n"
file_start = diff_lines.index(pattern) || diff_lines.index(pattern_with_tab)
```

but wasn't sure about the change in readability. Thoughts?

File: spec/fixtures/github_api/inline_comments_pr_diff.diff [hunk 2]
```diff
@@ -77,6 +77,17 @@ index 5817675..30499d7 100644
  * Show appropriate error message when GitHub repo was moved - KrauseFx
  * `danger plugins json [gem]` will now give gem metadata too - orta
  
+diff --git a/ios/Example/App Delegates/README.md b/ios/Example/App Delegates/README.md
+index 5817675..30499d7 100644
+--- a/ios/Example/App Delegates/README.md	
++++ b/ios/Example/App Delegates/README.md
```
Comment (daniel-beard) [inline spec/fixtures/github_api/inline_comments_pr_diff.diff]: Note: These two lines contain the trailing tabs. This is derived from a diff that I observed coming directly from Github Enterprise (although I reused the CHANGELOG.md contents here)

**Comment by orta** [comment]
I'll be making a release over the weekend probably
