### PR TITLE
Fix danger pr command cannot specify API host

### LINKED ISSUE #691: `danger pr` doesn't respect env variables, unable to use with GH Enterprise
# Report

## What did you do?
`danger pr https://internalgithub.website.com/org/repo/pulls/111`

## What did you expect to happen?
I expected `danger pr` to use `DANGER_GITHUB_API_HOST` to figure out what url to hit

## What happened instead?

It used `api.github.com` which does not work for GH enterprise instances.

```
/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/org/repo/pulls/287: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)]
```

## Your Environment

Danger 4.0.4, ruby 2.3.0

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Fixes #691.

After this PR, can specify API host by the following command:

```
$ DANGER_GITHUB_API_HOST=https://foo.bar.com https://foo.bar.com/org/repo/pulls/111
```

/cc @mtitolo

### CODE REVIEW

File: spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb [hunk 1]
```diff
@@ -103,5 +103,29 @@ def open_pull_requests_info
         expect(result.base).to eq "pr 518 base commit sha1"
       end
     end
+
+    context "specify api endpoint of octokit client" do
+      it "By DANGER_GITHUB_API_HOST" do
+        ENV["DANGER_GITHUB_API_HOST"] = "https://enterprise.artsy.net"
+
+        allow(Octokit::Client).to receive(:new).with(
```
Comment (hanneskaeufler) [inline spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb]: Is there a specific reason you picked `allow` versus `expect` here (and below)?

Comment (orta) [inline spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb]: If I recall - Allow is used to say "mock theses upcoming functions" basically, and expect says "perform upcoming expectations on this object"

**Comment by orta** [comment]
This looks 👍 to me

File: spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb (hunk 1 above)
Comment (hanneskaeufler) [inline spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb]: yeah I always regard `allow` as not an expectation, this would mean those two tests dont actually have an assertion in them (you could make it pass by removing all the production code from the method). However, I played around a bit with the tests and the way rspec seems to work this is not achievable so `allow` and `expect` is only a wording/intention difference here 👍

Comment (orta) [inline spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb]: nice one, thanks for the digging
