### PR TITLE
GitLab CI external repo

### LINKED ISSUE #1044: Github + Gitlab CI, get_repo_source is getting gitlab (it's a mirror), but the code is on github
# Report

## What did you do?

I want to run my tests on Gitlab CI through the Gitlab project mirror, I set the DANGER_GITHUB_API_TOKEN on Gitlab CI config. It executes the CI on Gitlab but fails asking for a DANGER_GITLAB_API_TOKEN

## What did you expect to happen?

I expected to not ask for a GITLAB token, since I don't want to open the PR/MR on Gitlab, but on Github.

## What happened instead?

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Fetching public_suffix 3.0.3
Installing public_suffix 3.0.3
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.1
Fetching claide 1.0.2
Installing claide 1.0.2
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.15.4
Installing faraday 0.15.4
Fetching faraday-http-cache 1.3.1
Installing faraday-http-cache 1.3.1
Fetching git 1.5.0
Installing git 1.5.0
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.13.0
Installing octokit 4.13.0
Fetching unicode-display_width 1.4.0
Installing unicode-display_width 1.4.0
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching danger 5.8.2
Installing danger 5.8.2
Fetching danger-plugin-api 1.0.0
Installing danger-plugin-api 1.0.0
Fetching danger-pep8 0.0.5
Installing danger-pep8 0.0.5
Fetching danger-todoist 1.3.0
Installing danger-todoist 1.3.0
Bundle complete! 3 Gemfile dependencies, 23 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
$ bundle exec danger
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
RuntimeError: No API token given, please provide one using `DANGER_GITLAB_API_TOKEN`
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/request_sources/gitlab.rb:31:in `client'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/ci_source/gitlab_ci.rb:40:in `determine_merge_request_id'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/ci_source/gitlab_ci.rb:31:in `validates_as_pr?'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:62:in `validate_pr!'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:46:in `validate!'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:21:in `run'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/commands/runner.rb:70:in `run'
  /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/bundle/gems/danger-5.8.2/bin/danger:5:in `<top (required)>'
  /usr/local/bundle/bin/danger:29:in `load'
  /usr/local/bundle/bin/danger:29:in `<top (required)>'
ERROR: Job failed: exit code 1
```

## Your Environment

* Which CI are you running on?

Gitlab CI.

* Are you running the latest version of Danger?

Yes.

* What is your Dangerfile?

Not relevant.

If I had a way of forcing using Github as the source of the project, the problem would go away, but it detects a gitlab uri because on gitlab you can set this mirror kind of project, any suggestions?

Thank you and kudos for the project!

### PR DESCRIPTION
**Pull request by philipqnguyen**
Resolves #1044

It is common for code repos to be hosted on Github while using
Gitlab only as a CI/CD service.

Info on using Gitlab only as CI/CD service for external repos:
https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/

Current limitations:
- Unfortunately, Gitlab currently does not expose the external repo's
url, so users will have to manually set the repo's URL as an ENV var
`DANGER_PROJECT_REPO_URL` 
(for ex., `DANGER_PROJECT_REPO_URL=https://github.com/procore/blueprinter`).
- Additionally, `RequestSources::Github#validates_as_ci?` is tricky now because
the `git remote -v` returns `origin` as `gitlab.com` rather than `github.com`. The
reasoning is that even though the actual repo is on Github.com, GitlabCI maintains a
mirror on Gitlab.com and the CI checkout the code from the Gitlab.com mirror.

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/danger/danger/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: lib/danger/ci_source/gitlab_ci.rb [hunk 1]
```diff
@@ -54,16 +61,29 @@ def self.determine_merge_request_id(env)
...
     def pull_request_id
-      @pull_request_id ||= self.class.determine_merge_request_id(@env)
+      @pull_request_id ||= self.class.determine_pull_or_merge_request_id(@env)
+    end
+
+    private
+
+    def slug_from(env)
+      if env["DANGER_PROJECT_REPO_URL"]
+        env["DANGER_PROJECT_REPO_URL"].split('/').last(2).join('/')
```
Comment (philipqnguyen) [inline lib/danger/ci_source/gitlab_ci.rb:83]: gitlab doesn't seem to give us any env var that points to the external repo's URL. It only points to gitlab's mirror URL. Users will need to set this ENV var themselves

File: lib/danger/request_sources/github/github.rb [hunk 2]
```diff
@@ -40,6 +40,10 @@ def get_pr_from_branch(repo_name, branch_name, owner)
         end
       end
 
+      def validates_as_ci?
+        true
+      end
```
Comment (philipqnguyen) [inline lib/danger/request_sources/github/github.rb:45]: In the base class, it is looking up the git remote origin to see if it contains `github.com`:
https://github.com/danger/danger/blob/61a09f84965edbb3a2150e5b1464fa6e39939fa7/lib/danger/request_sources/request_source.rb#L39-L42


Unfortunately, `RequestSources::Github#validates_as_ci?` is tricky now because
the `git remote -v` returns origin `gitlab.com` rather than `github.com`. The
reasoning is that even though the actual repo is on `Github.com`, GitlabCI maintains a
mirror on `Gitlab.com` and the CI checkout the code from there.

I could change this to also accept an origin that matches gitlab.com if the `ci_source` is Gitlab, however I am not sure I understand why there is a need to validate this at all, especially if we are already performing the `validates_as_api_source?`.

File: lib/danger/ci_source/gitlab_ci.rb [hunk 3]
```diff
@@ -54,16 +61,29 @@ def self.determine_merge_request_id(env)
 
     def initialize(env)
       @env = env
-      @repo_slug = env["CI_MERGE_REQUEST_PROJECT_PATH"] || env["CI_PROJECT_PATH"]
-      @project_url = env["CI_MERGE_REQUEST_PROJECT_URL"] || env["CI_PROJECT_URL"]
+      @repo_slug = slug_from(env)
+      @project_url = env["DANGER_PROJECT_REPO_URL"] || env["CI_MERGE_REQUEST_PROJECT_URL"] || env["CI_PROJECT_URL"]
```
Comment (philipqnguyen) [inline lib/danger/ci_source/gitlab_ci.rb:65]: On an unrelated note, there is a separate PR #1237 to remove this `project_url` as it does not seem to be used anymore.

File: CHANGELOG.md [hunk 4]
```diff
@@ -9,6 +9,7 @@
 -->
 
 ## master
+* Support external CI/CD for GitlabCI with Github code repository. To utilize this, please ensure `DANGER_GITHUB_API_TOKEN` and `DANGER_PROJECT_REPO_URL` are both set. [@philipqnguyen](https://github.com/philipqnguyen) [#1238](https://github.com/danger/danger/pull/1238)
```
Comment (yg) [inline CHANGELOG.md:12]: Brand Typo

```suggestion
* Support external CI/CD for GitLab CI with GitHub code repository. To utilize this, please ensure `DANGER_GITHUB_API_TOKEN` and `DANGER_PROJECT_REPO_URL` are both set. [@philipqnguyen](https://github.com/philipqnguyen) [#1238](https://github.com/danger/danger/pull/1238)
```

File: lib/danger/ci_source/gitlab_ci.rb [hunk 5]
```diff
@@ -15,7 +16,12 @@ module Danger
   # ```
   # ### Token Setup
   #
-  # Add the `DANGER_GITLAB_API_TOKEN` to your pipeline env variables.
+  # Add the `DANGER_GITLAB_API_TOKEN` to your pipeline env variables if you
+  # are hosting your code on Gitlab. If you are using Gitlab as a mirror
+  # for the purpose of CI/CD, while hosting your repo on Github, set the
```
Comment (yg) [inline lib/danger/ci_source/gitlab_ci.rb:21]: Brand Typo

```suggestion
  # are hosting your code on GitLab. If you are using GitLab as a mirror
  # for the purpose of CI/CD, while hosting your repo on GitHub, set the
```

**Comment by philipqnguyen** [comment]
I applied your suggestions @yg
Please let me know if anything else requires changing.

**Comment by philipqnguyen** [comment]
@orta What do you think of this and are there any changes you want to see?

File: lib/danger/request_sources/github/github.rb (hunk 2 above)
Comment (orta) [reply lib/danger/request_sources/github/github.rb:45]: I think this is probably reasonable

**Comment by orta** [comment]
If you rebase I'll merge 👍

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

File | Name|
--- | ---|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments deletes non-sticky comments if no violations are present|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments edits existing inline comment instead of creating a new one if file/line matches|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments deletes inline comments if those are no longer relevant|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments skips inline comments for files that are not part of the diff|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

File | Name|
--- | ---|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments edits existing inline comment instead of creating a new one if file/line matches|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments deletes non-sticky comments if no violations are present|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments deletes inline comments if those are no longer relevant|
<a href='https://github.com/philipqnguyen/danger/blob/a16b2098614b0481120d954aef6f5c504e04ff14/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response #update_pull_request! supports inline comments skips inline comments for files that are not part of the diff|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by philipqnguyen** [comment]
@orta, I rebased the PR, but tests are failing because a new `gitlab` gem was released on July 6th, v4.16.0, and it contains a bug: https://github.com/NARKOZ/gitlab/issues/574

I believe a solution would be to specify gitlab < 14.6.0

**Comment by orta** [comment]
Nah, not need to lock. I don't want to be accidentally missing something in the future by locking the version. I'm OK with CI being red until it's figured out, there's enough greens to validate that you didn't break something.

**Comment by NARKOZ** [comment]
> @orta, I rebased the PR, but tests are failing because a new `gitlab` gem was released on July 6th, v4.16.0, and it contains a bug: [NARKOZ/gitlab#574](https://github.com/NARKOZ/gitlab/issues/574)
> 
> I believe a solution would be to specify gitlab < 4.16.0

I've released version 4.16.1 with a fix.

**Comment by orta** [comment]
<3
